---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: proj-spark-airflow
 region: us-east-2
 version: "1.22"

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

managedNodeGroups:
- name: ng-on-demand
  desiredCapacity: 2
  minSize: 2
  maxSize: 4
  labels:
    lifecycle: OnDemand
  iam:
    withAddonPolicies:
      autoScaler: true
 
- name: ng-spot1
  desiredCapacity: 2
  minSize: 1
  maxSize: 4
  instanceTypes: ["m5.large","m4.large","m5a.large"]
  spot: true
  labels:
    lifecycle: Ec2Spot
